services:
  safe_app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.safe
    volumes: 
      - ./safe_app/:/code/
    ports:
      - 8002:8000
    env_file:
      - safe_app/.docker.env
    depends_on:
      - safe_database

  safe_database:
    image: postgres:16-alpine
    ports:
      - 5434:5432
    env_file:
      - safe_app/.docker.env
    volumes:
      - safe_postgres_data:/var/lib/postgresql/data/

  unsafe_app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.unsafe
    volumes:
      - ./unsafe_app/server/:/code/
    ports:
      - 8001:8000
    env_file:
      - unsafe_app/.docker.env

volumes:
  safe_postgres_data:
